export const TransactionType = Object.freeze({
	MONTHLY_DEPOSIT: 'MONTHLY_DEPOSIT',
	LOAN_DISBURSEMENT: 'LOAN_DISBURSEMENT',
	LOAN_REPAYMENT: 'LOAN_REPAYMENT',
	INTEREST_PAYMENT: 'INTEREST_PAYMENT',
	BANK_LOAN_RECEIVED: 'BANK_LOAN_RECEIVED',
	BANK_LOAN_REPAYMENT: 'BANK_LOAN_REPAYMENT',
	OPENING_BALANCE: 'OPENING_BALANCE',
	LUMP_SUM_CONTRIBUTION: 'LUMP_SUM_CONTRIBUTION',
	PENALTY_CHARGE: 'PENALTY_CHARGE',
});

export const MemberRole = Object.freeze({
	PRESIDENT: 'PRESIDENT',
	SECRETARY: 'SECRETARY',
	TREASURER: 'TREASURER',
	MEMBER: 'MEMBER',
});

export const MemberStatus = Object.freeze({
	ACTIVE: 'ACTIVE',
	INACTIVE: 'INACTIVE',
});
export const LoanStatus = Object.freeze({
	REQUESTED: 'REQUESTED',
	APPROVED: 'APPROVED',
	ONGOING: 'ONGOING',
	CLOSED: 'CLOSED',
	DEFAULTED: 'DEFAULTED',
});
export const LoanRepaymentStatus = Object.freeze({
	ONGOING: 'ONGOING',
	CLOSED: 'CLOSED',
});
export const AccountType = Object.freeze({
	EXTERNAL: 'EXTERNAL',
	SHG_CASH: 'SHG_CASH',
	MEMBER_SAVINGS: 'MEMBER_SAVINGS',
	MEMBER_LOAN: 'MEMBER_LOAN',
	BANK_LOAN: 'BANK_LOAN',
	INTEREST_INCOME: 'INTEREST_INCOME',
});
