export const categories = [
	{ id: 'all', label: 'सभी', emoji: '📋' },
	{ id: 'ssc', label: 'SSC', emoji: '🏛️' },
	{ id: 'railway', label: 'रेलवे', emoji: '🚂' },
	{ id: 'banking', label: 'बैंक', emoji: '🏦' },
	{ id: 'upsc', label: 'UPSC', emoji: '⭐' },
	{ id: 'mpstate', label: 'MP राज्य', emoji: '🏢' },
	{ id: 'defence', label: 'रक्षा', emoji: '🪖' },
	{ id: 'police', label: 'पुलिस', emoji: '👮' },
	{ id: 'teaching', label: 'शिक्षा', emoji: '📚' },
	{ id: 'health', label: 'स्वास्थ्य', emoji: '🏥' },
	{ id: 'psu', label: 'PSU', emoji: '🏭' },
];

export const jobs = [
	{
		id: 1,
		title: 'SSC CGL 2026',
		organization: 'Staff Selection Commission',
		department: 'विभिन्न केंद्रीय मंत्रालय/विभाग',
		category: 'ssc',
		vacancies: 17727,
		qualification: 'Graduation (किसी भी विषय में)',
		ageLimit: '18-32 वर्ष (OBC: 35, SC/ST: 37)',
		applicationStart: '2026-01-15',
		applicationEnd: '2026-04-15',
		examDate: '2026-06-15',
		salary: '₹25,500 - ₹1,51,100',
		applyLink: 'https://ssc.gov.in',
		posts: 'Inspector, Tax Assistant, Auditor, UDC, LDC',
		status: 'active',
		isNew: true,
	},
	{
		id: 2,
		title: 'SSC CHSL 2026',
		organization: 'Staff Selection Commission',
		department: 'डाक विभाग, विभिन्न मंत्रालय',
		category: 'ssc',
		vacancies: 6144,
		qualification: '12वीं पास (किसी भी विषय से)',
		ageLimit: '18-27 वर्ष',
		applicationStart: '2026-02-01',
		applicationEnd: '2026-03-31',
		examDate: '2026-05-20',
		salary: '₹25,500 - ₹81,100',
		applyLink: 'https://ssc.gov.in',
		posts: 'LDC, DEO, Postal Assistant, Sorting Assistant',
		status: 'active',
		isNew: true,
	},
	{
		id: 3,
		title: 'SSC GD Constable 2026',
		organization: 'Staff Selection Commission',
		department: 'CRPF, BSF, CISF, ITBP, SSB, AR, SSF',
		category: 'ssc',
		vacancies: 46617,
		qualification: '10वीं पास',
		ageLimit: '18-23 वर्ष',
		applicationStart: '2025-12-01',
		applicationEnd: '2026-03-28',
		examDate: '2026-04-20',
		salary: '₹21,700 - ₹69,100',
		applyLink: 'https://ssc.gov.in',
		posts: 'Constable GD in CAPF, NIA, SSF, AR',
		status: 'active',
		isNew: false,
	},
	{
		id: 4,
		title: 'SSC MTS 2026',
		organization: 'Staff Selection Commission',
		department: 'विभिन्न केंद्रीय कार्यालय',
		category: 'ssc',
		vacancies: 8326,
		qualification: '10वीं पास',
		ageLimit: '18-25 वर्ष',
		applicationStart: '2026-03-10',
		applicationEnd: '2026-05-10',
		examDate: '2026-07-01',
		salary: '₹18,000 - ₹56,900',
		applyLink: 'https://ssc.gov.in',
		posts: 'Multi Tasking Staff, Havaldar',
		status: 'upcoming',
		isNew: true,
	},
	{
		id: 5,
		title: 'RRB NTPC 2026',
		organization: 'Railway Recruitment Board',
		department: 'Indian Railways',
		category: 'railway',
		vacancies: 11558,
		qualification: 'Graduation (NTPC) / 12th (Level 2-5)',
		ageLimit: '18-33 वर्ष (post wise)',
		applicationStart: '2026-01-20',
		applicationEnd: '2026-04-20',
		examDate: '2026-07-15',
		salary: '₹19,900 - ₹63,200',
		applyLink: 'https://rrbcdg.gov.in',
		posts: 'Station Master, Goods Guard, Clerk, Typist',
		status: 'active',
		isNew: true,
	},
	{
		id: 6,
		title: 'RRB Group D (Level 1) 2026',
		organization: 'Railway Recruitment Board',
		department: 'Indian Railways',
		category: 'railway',
		vacancies: 32438,
		qualification: '10वीं पास + ITI (या 10th pass NAC holder)',
		ageLimit: '18-33 वर्ष',
		applicationStart: '2026-02-15',
		applicationEnd: '2026-04-30',
		examDate: '2026-08-01',
		salary: '₹18,000 - ₹56,900',
		applyLink: 'https://rrbcdg.gov.in',
		posts: 'Track Maintainer, Helper, Pointsman, Gateman',
		status: 'active',
		isNew: false,
	},
	{
		id: 7,
		title: 'RRB JE / SSE 2026',
		organization: 'Railway Recruitment Board',
		department: 'Indian Railways',
		category: 'railway',
		vacancies: 7951,
		qualification: 'Diploma / B.Tech (Engineering)',
		ageLimit: '18-33 वर्ष',
		applicationStart: '2026-03-01',
		applicationEnd: '2026-05-15',
		examDate: '2026-09-01',
		salary: '₹35,400 - ₹1,12,400',
		applyLink: 'https://rrbcdg.gov.in',
		posts: 'Junior Engineer, Senior Section Engineer',
		status: 'upcoming',
		isNew: true,
	},
	{
		id: 8,
		title: 'RRB ALP (Loco Pilot) 2026',
		organization: 'Railway Recruitment Board',
		department: 'Indian Railways',
		category: 'railway',
		vacancies: 5696,
		qualification: '10वीं + ITI / Diploma (Mechanical/Electrical)',
		ageLimit: '18-30 वर्ष',
		applicationStart: '2026-02-01',
		applicationEnd: '2026-04-15',
		examDate: '2026-07-20',
		salary: '₹25,500 - ₹81,100',
		applyLink: 'https://rrbcdg.gov.in',
		posts: 'Assistant Loco Pilot',
		status: 'active',
		isNew: false,
	},
	{
		id: 9,
		title: 'IBPS PO 2026',
		organization: 'Institute of Banking Personnel Selection',
		department: 'Public Sector Banks',
		category: 'banking',
		vacancies: 4455,
		qualification: 'Graduation (किसी भी विषय में)',
		ageLimit: '20-30 वर्ष',
		applicationStart: '2026-08-01',
		applicationEnd: '2026-09-15',
		examDate: '2026-10-15',
		salary: '₹36,000 - ₹63,840 (starting)',
		applyLink: 'https://ibps.in',
		posts: 'Probationary Officer / Management Trainee',
		status: 'upcoming',
		isNew: false,
	},
	{
		id: 10,
		title: 'IBPS Clerk 2026',
		organization: 'Institute of Banking Personnel Selection',
		department: 'Public Sector Banks',
		category: 'banking',
		vacancies: 6128,
		qualification: 'Graduation (किसी भी विषय में)',
		ageLimit: '20-28 वर्ष',
		applicationStart: '2026-07-15',
		applicationEnd: '2026-08-30',
		examDate: '2026-09-20',
		salary: '₹22,000 - ₹45,000 (starting)',
		applyLink: 'https://ibps.in',
		posts: 'Clerk / Junior Associate',
		status: 'upcoming',
		isNew: false,
	},
	{
		id: 11,
		title: 'SBI PO 2026',
		organization: 'State Bank of India',
		department: 'SBI',
		category: 'banking',
		vacancies: 2000,
		qualification: 'Graduation (किसी भी विषय में)',
		ageLimit: '21-30 वर्ष',
		applicationStart: '2026-03-01',
		applicationEnd: '2026-04-15',
		examDate: '2026-06-01',
		salary: '₹41,960 - ₹63,840 (starting CTC ~₹8.6 LPA)',
		applyLink: 'https://sbi.co.in/careers',
		posts: 'Probationary Officer',
		status: 'active',
		isNew: true,
	},
	{
		id: 12,
		title: 'UPSC Civil Services 2026',
		organization: 'Union Public Service Commission',
		department: 'IAS, IPS, IFS एवं अन्य',
		category: 'upsc',
		vacancies: 1056,
		qualification: 'Graduation (किसी भी विषय में)',
		ageLimit: '21-32 वर्ष (OBC: 35, SC/ST: 37)',
		applicationStart: '2026-02-15',
		applicationEnd: '2026-03-31',
		examDate: '2026-05-25',
		salary: '₹56,100 - ₹2,50,000',
		applyLink: 'https://upsc.gov.in',
		posts: 'IAS, IPS, IFS, IRS और 24+ सेवाएं',
		status: 'active',
		isNew: true,
	},
	{
		id: 13,
		title: 'UPSC CDS 2026 (I)',
		organization: 'Union Public Service Commission',
		department: 'Indian Army, Navy, Air Force',
		category: 'upsc',
		vacancies: 457,
		qualification: 'Graduation (IMA/OTA), Engineering (Naval/Air Force)',
		ageLimit: '19-25 वर्ष (OTA: 19-27)',
		applicationStart: '2025-12-15',
		applicationEnd: '2026-01-31',
		examDate: '2026-04-13',
		salary: '₹56,100 - ₹1,77,500',
		applyLink: 'https://upsc.gov.in',
		posts: 'IMA, OTA, Naval Academy, Air Force Academy',
		status: 'active',
		isNew: false,
	},
	{
		id: 14,
		title: 'UPSC NDA 2026 (I)',
		organization: 'Union Public Service Commission',
		department: 'National Defence Academy',
		category: 'upsc',
		vacancies: 400,
		qualification: '12वीं पास (PCM for Air Force/Navy)',
		ageLimit: '16.5 - 19.5 वर्ष',
		applicationStart: '2025-12-20',
		applicationEnd: '2026-02-10',
		examDate: '2026-04-06',
		salary: 'Training stipend ₹56,100/month',
		applyLink: 'https://upsc.gov.in',
		posts: 'Army, Navy, Air Force Cadet',
		status: 'active',
		isNew: false,
	},
	{
		id: 15,
		title: 'MPPSC State Services 2026',
		organization: 'MP Public Service Commission',
		department: 'मध्य प्रदेश शासन',
		category: 'mpstate',
		vacancies: 583,
		qualification: 'Graduation (किसी भी विषय में)',
		ageLimit: '21-40 वर्ष (OBC: 43, SC/ST: 45)',
		applicationStart: '2026-01-10',
		applicationEnd: '2026-03-10',
		examDate: '2026-05-18',
		salary: '₹36,200 - ₹1,51,100',
		applyLink: 'https://mppsc.mp.gov.in',
		posts: 'DSP, SDM, Naib Tehsildar, BDO और अन्य',
		status: 'active',
		isNew: true,
	},
	{
		id: 16,
		title: 'MP Patwari भर्ती 2026',
		organization: 'MPPEB (Vyapam)',
		department: 'राजस्व विभाग, MP',
		category: 'mpstate',
		vacancies: 2736,
		qualification: 'Graduation + CCC Certificate',
		ageLimit: '18-40 वर्ष',
		applicationStart: '2026-02-20',
		applicationEnd: '2026-04-05',
		examDate: '2026-06-01',
		salary: '₹22,000 - ₹35,000',
		applyLink: 'https://peb.mp.gov.in',
		posts: 'पटवारी',
		status: 'active',
		isNew: true,
	},
	{
		id: 17,
		title: 'MP संविदा शिक्षक Varg 3 (2026)',
		organization: 'MPPEB (Vyapam)',
		department: 'स्कूल शिक्षा विभाग, MP',
		category: 'teaching',
		vacancies: 18571,
		qualification: '12वीं + D.El.Ed / B.Ed',
		ageLimit: '18-40 वर्ष',
		applicationStart: '2026-03-01',
		applicationEnd: '2026-04-30',
		examDate: '2026-06-15',
		salary: '₹22,000 - ₹32,000',
		applyLink: 'https://peb.mp.gov.in',
		posts: 'प्राथमिक शिक्षक (कक्षा 1-5)',
		status: 'upcoming',
		isNew: true,
	},
	{
		id: 18,
		title: 'MP Police Constable 2026',
		organization: 'MPPEB (Vyapam)',
		department: 'MP Police',
		category: 'police',
		vacancies: 7090,
		qualification: '10वीं पास',
		ageLimit: '18-28 वर्ष',
		applicationStart: '2026-01-25',
		applicationEnd: '2026-03-25',
		examDate: '2026-05-10',
		salary: '₹19,500 - ₹62,000',
		applyLink: 'https://peb.mp.gov.in',
		posts: 'Constable (GD), Constable (Radio)',
		status: 'active',
		isNew: false,
	},
	{
		id: 19,
		title: 'MP Police SI भर्ती 2026',
		organization: 'MPPEB (Vyapam)',
		department: 'MP Police',
		category: 'police',
		vacancies: 1546,
		qualification: 'Graduation',
		ageLimit: '21-28 वर्ष',
		applicationStart: '2026-03-15',
		applicationEnd: '2026-05-15',
		examDate: '2026-07-20',
		salary: '₹36,200 - ₹1,14,800',
		applyLink: 'https://peb.mp.gov.in',
		posts: 'Sub Inspector (Civil/Wireless)',
		status: 'upcoming',
		isNew: true,
	},
	{
		id: 20,
		title: 'Indian Army Agniveer 2026',
		organization: 'Indian Army',
		department: 'Ministry of Defence',
		category: 'defence',
		vacancies: 46000,
		qualification: '10वीं / 12वीं पास (trade wise)',
		ageLimit: '17.5 - 21 वर्ष',
		applicationStart: '2026-01-15',
		applicationEnd: '2026-03-30',
		examDate: 'Rally Schedule अनुसार',
		salary: '₹30,000 - ₹40,000/month + Seva Nidhi ₹11.71 lakh',
		applyLink: 'https://joinindianarmy.nic.in',
		posts: 'Agniveer GD, Technical, Clerk, Tradesman',
		status: 'active',
		isNew: false,
	},
	{
		id: 21,
		title: 'Indian Navy Agniveer SSR/MR 2026',
		organization: 'Indian Navy',
		department: 'Ministry of Defence',
		category: 'defence',
		vacancies: 3000,
		qualification: '10वीं (MR) / 12वीं PCM (SSR)',
		ageLimit: '17.5 - 21 वर्ष',
		applicationStart: '2026-02-01',
		applicationEnd: '2026-03-15',
		examDate: '2026-04-10',
		salary: '₹30,000 - ₹40,000/month',
		applyLink: 'https://joinindiannavy.gov.in',
		posts: 'Agniveer SSR, Agniveer MR',
		status: 'active',
		isNew: true,
	},
	{
		id: 22,
		title: 'CTET 2026 (January)',
		organization: 'CBSE',
		department: 'Ministry of Education',
		category: 'teaching',
		vacancies: 'Eligibility Test',
		qualification: 'Graduation + B.Ed / D.El.Ed',
		ageLimit: 'कोई आयु सीमा नहीं',
		applicationStart: '2025-11-15',
		applicationEnd: '2026-01-10',
		examDate: '2026-01-21',
		salary: 'Eligibility Certificate (Teaching jobs के लिए जरूरी)',
		applyLink: 'https://ctet.nic.in',
		posts: 'Paper I (कक्षा 1-5), Paper II (कक्षा 6-8)',
		status: 'active',
		isNew: false,
	},
	{
		id: 23,
		title: 'MP ANM/GNM भर्ती 2026',
		organization: 'NHM MP',
		department: 'स्वास्थ्य विभाग, MP',
		category: 'health',
		vacancies: 4500,
		qualification: 'ANM / GNM / B.Sc Nursing',
		ageLimit: '18-40 वर्ष',
		applicationStart: '2026-03-01',
		applicationEnd: '2026-04-30',
		examDate: 'Interview based',
		salary: '₹15,000 - ₹32,000',
		applyLink: 'https://nhmmp.gov.in',
		posts: 'ANM, Staff Nurse, GNM',
		status: 'upcoming',
		isNew: true,
	},
	{
		id: 24,
		title: 'NTPC Executive Trainee 2026',
		organization: 'NTPC Limited',
		department: 'Ministry of Power',
		category: 'psu',
		vacancies: 864,
		qualification: 'B.Tech / B.E. (GATE score required)',
		ageLimit: '27 वर्ष',
		applicationStart: '2026-02-10',
		applicationEnd: '2026-03-25',
		examDate: 'GATE 2026 score based',
		salary: '₹60,000 - ₹1,80,000/month (CTC ~₹15 LPA)',
		applyLink: 'https://ntpc.co.in/careers',
		posts: 'Executive Trainee (Engineering)',
		status: 'active',
		isNew: true,
	},
	{
		id: 25,
		title: 'BHEL Engineer Trainee 2026',
		organization: 'Bharat Heavy Electricals Limited',
		department: 'Ministry of Heavy Industries',
		category: 'psu',
		vacancies: 200,
		qualification: 'B.Tech / B.E. (GATE score required)',
		ageLimit: '27 वर्ष',
		applicationStart: '2026-02-15',
		applicationEnd: '2026-04-01',
		examDate: 'GATE 2026 score based',
		salary: '₹50,000 - ₹1,60,000/month (CTC ~₹12 LPA)',
		applyLink: 'https://bhel.com/careers',
		posts: 'Engineer Trainee (Bhopal, Jhansi plants)',
		status: 'active',
		isNew: false,
	},
];
